### ISSUE TITLE
Update ImageBuilder commands that use Service Principal authentication

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1264]
Commands that need to be updated:
- [x] [CopyImages](https://github.com/dotnet/docker-tools/blob/10c82d12cf90e24693067e9768eab929153e1fa2/src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs#L31) - @lbussell 
  - [x] https://github.com/dotnet/docker-tools/pull/1261
  - [x] https://github.com/dotnet/docker-tools/pull/1260
  - [x] https://github.com/dotnet/dotnet-docker/pull/5421
- [x] [CleanAcrImages](https://github.com/dotnet/docker-tools/blob/99579deabbf928327291d8cd4271aa486bd34660/src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs#L39) - @mthalman 
    - [x] https://github.com/dotnet/docker-tools/pull/1272
    - [x] https://github.com/dotnet/docker-tools/pull/1271
- [x] [WaitForMcrDocIngestion](https://github.com/dotnet/docker-tools/blob/99579deabbf928327291d8cd4271aa486bd34660/src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrDocIngestionOptions.cs#L46) and [WaitForMcrImageIngestionOptions](https://github.com/dotnet/docker-tools/blob/99579deabbf928327291d8cd4271aa486bd34660/src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionOptions.cs#L44) - @lbussell 
    - [x] https://github.com/dotnet/docker-tools/pull/1269
    - [x] https://github.com/dotnet/docker-tools/pull/1271
- [x] [Build](https://github.com/dotnet/docker-tools/blob/99579deabbf928327291d8cd4271aa486bd34660/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs#L38) - @lbussell 
    - [x] https://github.com/dotnet/docker-tools/pull/1293
- [x] [IngestKustoImageInfo](https://github.com/dotnet/docker-tools/blob/99579deabbf928327291d8cd4271aa486bd34660/src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs#L46) - @mthalman
    - [x] https://github.com/dotnet/docker-tools/pull/1277
- [x] [Test jobs](https://github.com/dotnet/docker-tools/blob/8fa3fbfc2048a893dfeb6a1f9a1786546c77534f/eng/common/templates/steps/test-images-linux-client.yml#L45-L50)
    - [x] https://github.com/dotnet/docker-tools/pull/1290

**Comment by lbussell** [comment]
These are all completed and there are now some successful pipeline runs in this repo as well as dotnet-docker that don't use service principal creds directly.
