### ISSUE TITLE
Upgrade testrunner image to Azure Linux 3.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1513]
The testrunner image is currently based on Mariner 2.0:

https://github.com/dotnet/docker-tools/blob/3a078d892227e6446a5bcaf13536b8e37934685d/eng/common/templates/variables/docker-images.yml#L5

 This should be upgraded to Azure Linux 3.0.

## Tasks

- [x] Add new image to buildtools-prereqs - https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1287
- [ ] Migrate pipelines to using new image - https://github.com/dotnet/docker-tools/pull/1519
- [ ] Clean up old image from buildtools-prereqs
