### ISSUE TITLE
Create issue templates for tracking the steps to a release

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#383]
The template should list out the checkbox steps to a release.  We should be utilizing these templates to create issues for each release.  It may make sense to have multiple templates for the types of releases: .NET Core, patch Tuesday, etc.

These issues will help capture the steps so that anyone could perform a release.

### .NET Core

- [x] Patch Tuesday release (dotnet/dotnet-docker/pull/1633)
- [x] .NET Core release (dotnet/dotnet-docker/pull/1633)
- [ ] New distro/OS release

### .NET Fx
- [x] Patch Tuesday release (microsoft/dotnet-framework-docker/pull/506)
- [x] VS tools release (microsoft/dotnet-framework-docker/pull/506)
- [x] New Windows version release
